export const originalObject = {
    certificateId: "",
    claimTemplateId: "",
    claimReason: "",
    primaryInsured: {
        name: "",
        dateOfBirth: "",
        certificateNumber: "",
        emailAddress: "",
        phone: "",
        fax: "",
        mailingAddress: "",
        mailingCity: "",
        mailingState: "",
        mailingPostalCode: "",
        homeAddress: "",
        homeCity: "",
        homeState: "",
        homePostalCode: "",
        preferredContactMethod: "",
    },
    travelInformation: {
        confirmationNumber: "",
        bookingNumber: "",
        dateOfDeparture: "",
        dateOfReturn: "",
        originalDestination: "",
        travelSupplier: "",
        dateOfFirstPayment: "",
    },
    claimedExpenses: {
        airfare: "",
        childcare: "",
        cruise: "",
        deposit: "",
        eventTicket: "",
        hotel: "",
        lodging: "",
        rentalCar: "",
        tour: "",
        other: "",
        totalExpenses: "",
        refunds: "",
        totalClaimed: "",
    },
    travelVouchers: {
        hasVouchers: "",
        useVouchers: "",
        voucherEntity1: "",
        voucherNumber1: "",
        voucherEntity2: "",
        voucherNumber2: "",
        voucherEntity3: "",
        voucherNumber3: "",
    },
    travelCompanions: [],
    reasonForCancellation: "",
    medicalCancellation: {
        name: "",
        dateOfBirth: "",
        relationshipToPrimary: "",
        isPrimary: "",
        dateOfLastTreatment: "",
        hospitalizationPeriod: {
            startDate: "",
            endDate: "",
        },
    },
    otherInsurance: {
        otherInsurance: "",
        name: "",
        address: "",
        city: "",
        state: "",
        postalCode: "",
        policyNumber: "",
        phone: "",
    }
};
export const mapList = ["TripCancellation", "TripInterruption", "TripDelayAndMissedConnection", "TripDelay", "TripCancellationForAnyReason", "EFEducationalTours", "SingleSupplement", "GoAheadTours", "EventTicketRegistrationFeeProtection", "UltimateBreak", "TripInterruptionForAnyReason", "CollegeStudyTours", "PetKennel", "GapYear", "PrimaryInsuredName", "ExploreAmerica", "PrimaryInsuredDateOfBirth", "PrimaryInsuredPolicyNumber", "PrimaryInsuredCertificateNumber", "PrimaryInsuredPhoneNumber", "PrimaryInsuredEmailAddress", "PrimaryInsuredFaxNumber", "PrimaryInsuredMailingAddress", "PrimaryInsuredCityOne", "PrimaryInsuredStateOne", "PrimaryInsuredZipCodeOne", "PrimaryInsuredHomeAddress", "PrimaryInsuredStateProvinceRegionOne", "PrimaryInsuredCityTwo", "PrimaryInsuredPostalCodeOne", "PrimaryInsuredStateTwo", "PrimaryInsuredZipCodeTwo", "PrimaryInsuredPreferredMethodOfContactMail", "PrimaryInsuredStateProvinceRegionTwo", "PrimaryInsuredPreferredMethodOfContactEmail", "PrimaryInsuredPostalCodeTwo", "PrimaryInsuredPreferredMethodOfContactPhone", "ProviderCompanyName", "ScheduledDateOfDeparture", "ProviderPhoneNumber", "ScheduledDateOfReturn", "ProviderAddress", "ActualDateOfDeparture", "ConfirmationNumber", "ProviderCity", "ActualDateOfReturn", "BookingNumber", "ProviderState", "DateOfDeparture", "ProviderZipCode", "DateOfReturn", "DateTravelArrangementsMade", "AirfareAmount", "OriginalDestination", "DateOfInitialPayment", "ChildcareAmount", "TravelSupplier", "CruiseshipAmount", "PaymentForLandSeaAirArrangements", "DepositAmount", "EventTicketAmount", "HotelAmount", "LodgingAmount", "MedicalTreatmentAmount", "PrescriptionsAmount", "TourAmount", "RentalCarAmount", "OtherAmount", "TotalExpensesAmount", "RefundAmount", "TotalClaimedAmount", "RefundsAmount", "NotClaimingAirlineTickets", "WillBeClaimingAirlineTickets", "DidReceiveCreditVoucherTrue", "CompanionNameOne", "DidReceiveCreditVoucherFalse", "CompanionNameTwo", "WillUseCreditVoucherTrue", "CompanionNameThree", "WillUseCreditVoucherFalse", "CompanionNameFour", "CreditVoucherIssuerNameOne", "TravelCompanionPolicyNumberOne", "TravelingCompanionCertificateNumberOne", "CreditVoucherIssuerNameTwo", "TravelCompanionPolicyNumberTwo", "TravelingCompanionCertificateNumberTwo", "CreditVoucherIssuerNameThree", "TravelCompanionRelationshipOne", "TravelCompanionPolicyNumberThree", "TravelingCompanionCertificateNumberThree", "CreditOrVoucherNumberOne", "TravelCompanionRelationshipTwo", "TravelCompanionPolicyNumberFour", "TravelingCompanionCertificateNumberFour", "CreditOrVoucherNumberTwo", "TravelCompanionRelationshipThree", "ReasonForCancellationDelayInterruption", "CreditOrVoucherNumberThree", "TravelCompanionRelationshipFour", "InsuredName", "InsuredDateOfBirth", "InsuredRelationshipToPrimary", "YesReceivedMedicalAttention", "LastTreatmentDate", "CreditOrVoucherNumberFour", "NoReceivedMedicalAttention", "PeriodOfHospitalizationFrom", "CreditOrVoucherNumberFive", "DateLastTreated", "PeriodOfHospitalizationTo", "CreditOrVoucherNumberSix", "CreditOrVoucherNumberSeven", "CreditOrVoucherNumberEight", "InsuredSignatureDate", "CreditOrVoucherNumberNine", "InsuredSignature", "CreditOrVoucherNumberTen", "TravelCompanionCertificateOne", "TravelCompanionCertificateTwo", "OtherInsuranceName", "TravelCompanionCertificateThree", "OtherInsurancePlanNumber", "TravelCompanionCertificateFour", "HasOtherInsuranceTrue", "OtherInsuranceTelephone", "TravelCompanionCertificateFive", "HasOtherInsuranceFalse", "TravelCompanionCertificateSix", "TravelCompanionCertificateSeven", "TravelCompanionCertificateEight", "OtherInsuranceCreditCardBank", "TravelCompanionCertificateNine", "TravelCompanionCertificateTen", "IsClaimingOnBehalfOfTravelCompanionOneTrue", "IsClaimingOnBehalfOfTravelCompanionOneFalse", "IsClaimingOnBehalfOfTravelCompanionTwoTrue", "IsClaimingOnBehalfOfTravelCompanionTwoFalse", "IsClaimingOnBehalfOfTravelCompanionThreeTrue", "IsClaimingOnBehalfOfTravelCompanionThreeFalse", "IsClaimingOnBehalfOfTravelCompanionFourTrue", "IsClaimingOnBehalfOfTravelCompanionFourFalse", "IsClaimingOnBehalfOfTravelCompanionFiveTrue", "IsClaimingOnBehalfOfTravelCompanionFiveFalse", "IsClaimingOnBehalfOfTravelCompanionSixTrue", "IsClaimingOnBehalfOfTravelCompanionSixFalse", "IsClaimingOnBehalfOfTravelCompanionSevenTrue", "IsClaimingOnBehalfOfTravelCompanionSevenFalse", "IsClaimingOnBehalfOfTravelCompanionEightTrue", "IsClaimingOnBehalfOfTravelCompanionEightFalse", "IsClaimingOnBehalfOfTravelCompanionNineTrue", "IsClaimingOnBehalfOfTravelCompanionNineFalse", "IsClaimingOnBehalfOfTravelCompanionTenTrue", "IsClaimingOnBehalfOfTravelCompanionTenFalse", "RelationshipToPrimaryInsured", "SameAsPrimaryInsured", "HospitalizationStartDate", "HospitalizationEndDate", "OtherInsuranceAddress", "OtherInsuranceCity", "OtherInsuranceState/Province/Region", "OtherInsurancePostalCode", "OtherInsurancePolicyNumber", "OtherInsurancePhoneNumber", "InsuredSignatureDate"]